### ISSUE TITLE
Problem traceback

### ISSUE THREAD

**Issue by Venceslao** [mkbrutusproject/MKBRUTUS#2]
Hi i try to use mkbrutus to test my router but i have this issue:
# python mkbrutus.py -t (my router ip) -p 8291 -u admin -d 500.txt

```
      _   _   _   _  _____  ____ _   _  ____ _   _ _____
     |  \/  || | / /| ___ \ ___ \ | | |_   _| | | /  ___|
     | .  . || |/ / | |_/ / |_/ / | | | | | | | | \ `--.
     | |\/| ||    \ | ___ \    /| | | | | | | | | |`--. \
     | |  | || |\  \| |_/ / |\ \| |_| | | | | |_| /\__/ /
     \_|  |_/\_| \_/\____/\_| \_|\___/  \_/  \___/\____/

                  Mikrotik RouterOS Bruteforce Tool 1.0.2
       Ramiro Caire (@rcaire) & Federico Massa (@fgmassa)
                http://mkbrutusproject.github.io/MKBRUTUS
```
## [*] Starting bruteforce attack...

Traceback (most recent call last):
  File "mkbrutus.py", line 363, in <module>
    main()
  File "mkbrutus.py", line 329, in main
    defaultcreds = apiros.login("admin", "")
  File "mkbrutus.py", line 103, in login
    for repl, attrs in self.talk(["/login"]):
  File "mkbrutus.py", line 116, in talk
    i = self.readSentence();
  File "mkbrutus.py", line 140, in readSentence
    w = self.readWord()
  File "mkbrutus.py", line 149, in readWord
    ret = self.readStr(self.readLen())
  File "mkbrutus.py", line 178, in readLen
    c = ord(self.readStr(1))
  File "mkbrutus.py", line 219, in readStr
    s = self.sk.recv(length - len(ret))
socket.timeout: timed out

Thanks for youre time.

**Comment by rcaire** [comment]
Hi,
It´s a socket timeout due to the fact that MKBRUTUS works currently through
API port (8728/TCP) only, not winbox port (8291).
It is true that the error output should not be noisy, we are currently
working on that ;) as well as support to test against HTTP, SSH & TELNET
protocols too (maybe winbox).

Cheers
Ramiro

2015-06-17 13:39 GMT-03:00 Venceslao notifications@github.com:

> Hi i try to use mkbrutus to test my router but i have this issue:
> 
> #python mkbrutus.py -t (my router ip) -p 8291 -u admin -d 500.txt
> 
> ---
> 
> | \/ || | / /| ___ \ ___ \ | | |_ _| | | / ___|
> | . . || |/ / | |_/ / |_/ / | | | | | | | | \ --.
> | |\/| || \ | ___ \ /| | | | | | | | | |--. \
> | | | || |\ | |_/ / |\ | |_| | | | | |_| /__/ /
> _| |_/\_| _/____/_| _|___/ _/ ___/____/
> 
> ```
>               Mikrotik RouterOS Bruteforce Tool 1.0.2
>    Ramiro Caire (@rcaire) & Federico Massa (@fgmassa)
>             http://mkbrutusproject.github.io/MKBRUTUS
> ```
> 
> [*] Starting bruteforce attack...
> 
> Traceback (most recent call last):
> File "mkbrutus.py", line 363, in
> main()
> File "mkbrutus.py", line 329, in main
> defaultcreds = apiros.login("admin", "")
> File "mkbrutus.py", line 103, in login
> for repl, attrs in self.talk(["/login"]):
> File "mkbrutus.py", line 116, in talk
> i = self.readSentence();
> File "mkbrutus.py", line 140, in readSentence
> w = self.readWord()
> File "mkbrutus.py", line 149, in readWord
> ret = self.readStr(self.readLen())
> File "mkbrutus.py", line 178, in readLen
> c = ord(self.readStr(1))
> File "mkbrutus.py", line 219, in readStr
> s = self.sk.recv(length - len(ret))
> socket.timeout: timed out
> 
> Thanks for youre time.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mkbrutusproject/MKBRUTUS/issues/2.

## 

Ramiro J. Caire

Analista en Seguridad Informática
PGP: 0xA657B4362D357BEC
Twitter: @rcaire

**Comment by adityachintha** [comment]
I am Eagerly waiting to test it for the HTTP, SSH & TELNET and Winbox !!!! :D .. I Would like to test it In Windows and want to support you guys Ramiro!!

**Comment by xros** [comment]
@rcaire 

Usually a RouterOS router only open port 2000 and 8291(winbox) for maintenance. 

hey, did you guys finish the work for the support of (HTTP/SSH/TELNET/Winbox)?
